### ISSUE TITLE
Запрос на добавление функционала: автоматическое изменение диапазона выдачи новых IP по DHCP при каждой новой фиксации статического IP

### ISSUE THREAD

**Issue by aofodo** [JKearnsl/DHCPStaticMapper#3]
![image](https://github.com/JKearnsl/DHCPStaticMapper/assets/165767272/7f60c775-d006-443d-a504-0f8a0e4de5ce)

У OPNsense есть баг, который заключается в том, что при назначения статического IP узлу из диапазона, который указан в настройках DHCP, данный IP по прежнему остаётся свободный для дальнейшей выдачи. В результате, после фиксации статического IP нескольким узлам, если появляется новый узел, которому необходимо выдать по DHCP новый IP, OPNsense возьмёт его из указанного в настройках диапазона, несмотря на то, что данный IP уже статически закреплён за другим узлом. В итоге такая попытка назначения IP будет неудачной и OPNsense попытается повторить её  снова со следующим IP адресом. Это будет продолжать не более 3-х раз, а затем OPNsense откажет в выдаче IP адреса

Решение: необходимо при каждой новой фиксации статического IP сдвигать нижнею границу указанного в настройках диапазона IP до актуальной (чтобы не было ни одного статического IP в итоговом диапазоне)

В случае, если весь диапазон IP оказался исчерпан, то необходимо сообщить об этом в логах с уровнем ERROR и не сдвигать границу диапазона

Весь данный функционал должен быть опционален и активироваться через конфигурацию DHCPStaticMapper'а

**Comment by aofodo** [comment]
@whitekeep

**Comment by JKearnsl** [comment]
Has been fixed in opensense v24+
